# Generated by Django 4.2.11 on 2024-04-24 18:29

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='ID письма')),
                ('mailbox', models.EmailField(max_length=254, verbose_name='Почтовый аккаунт')),
                ('sender', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('recipient', models.EmailField(blank=True, max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('sent', models.DateTimeField(verbose_name='Время отправки')),
                ('received', models.DateTimeField(verbose_name='Время получения')),
                ('text', models.TextField(blank=True, verbose_name='Текст письма')),
                ('attachments', models.JSONField(blank=True, verbose_name='Список вложений')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-received'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почтовый аккаунт')),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=128, verbose_name='Пароль'))),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['email'],
            },
        ),
    ]
